"""Added Telegram User id

Revision ID: a984e8dfd640
Revises: 09e613253ab5
Create Date: 2025-02-23 03:36:37.343894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a984e8dfd640'
down_revision: Union[str, None] = '09e613253ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###
